### Conduct the QR iteration for matrix A in example 1 of section 9.5 and estimate the eigenvalues.

In [32]:
import numpy as np
import scipy.linalg as lin

In [36]:
A = np.array([[3, 1, 0], [1, 3, 1], [0, 1, 3]]) 
eigval, eigvec =  lin.eig(A) # calculate the actual eigenvalues
print('The actaual eigenvalues of the matrix A:')
for val in eigval:
    print(val)

The actaual eigenvalues of the matrix A:
(1.585786437626906+0j)
(2.999999999999999+0j)
(4.414213562373095+0j)


In [37]:
# https://pythonnumericalmethods.berkeley.edu/notebooks/chapter15.03-The-QR-Method.html
n = [1, 5, 10, 20] # list of number of iterations
# QR method
for i in range(22):
    q, r = lin.qr(A)
    A = np.dot(r, q)
    if i+1 in n:
        print(f'Iteration {i+1}:')
        print(A)

Iteration 1:
[[ 3.60000000e+00  8.60232527e-01 -5.55111512e-17]
 [ 8.60232527e-01  3.12972973e+00 -8.97403120e-01]
 [ 0.00000000e+00 -8.97403120e-01  2.27027027e+00]]
Iteration 5:
[[ 4.35705755e+00  2.78749764e-01 -1.61329283e-16]
 [ 2.78749764e-01  3.05225459e+00 -8.39664040e-02]
 [ 0.00000000e+00 -8.39664040e-02  1.59068786e+00]]
Iteration 10:
[[4.41296468e+00 4.20074873e-02 1.47058472e-16]
 [4.20074873e-02 3.00124067e+00 3.40764046e-03]
 [0.00000000e+00 3.40764046e-03 1.58579464e+00]]
Iteration 20:
[[4.41421301e+00 8.83869413e-04 1.44638688e-16]
 [8.83869413e-04 3.00000055e+00 5.80094798e-06]
 [0.00000000e+00 5.80094798e-06 1.58578644e+00]]


In [35]:
print("The estimated eigenvalues of A by QR method:")
print(str(A[0][0]))
print(str(A[1][1]))
print(str(A[2][2]))

The estimated eigenvalues of A by QR method:
4.414213444522127
3.000000117849117
1.5857864376287631
